#! /bin/sh

# to run: sh compile

#index file
index_file=../../index.php

#js compressed output file
js_output_file=../../resources/js/script.min.js
# js compiler (currently closeure)
compiler=`pwd`/compiler.jar

#search for resources/js/src/(\w\d-/.).js
pattern="resources\/js\/src\/\(\w\|\d\|-\|/\|\.\)*.js"

#search in index.php for script src includes that match pattern
#use matches to build command
for file in `grep -o $pattern $index_file` ; do
	scripts="$scripts --js=../../$file"
done

#build java command to compile scripts using closure compiler
cmd="java -jar $compiler $scripts --js_output_file=$js_output_file"
#for debugging
#echo $cmd

#run command
$cmd

#output success
echo "$js_output_file build complete"
