#! /bin/sh

# to run: sh compile
# to run specific page: sh compile coming-soon.php coming-soon.min.js 
#	=> coming-soon.php is the file name
#	=> coming-soon.min.js is the compressed output file

#index file is default
filename=index.php
if [ $1 ]; then
	filename=$1
fi

index_file=../../$filename

#js compressed output file
# script.min.js is default
scriptfile="script.min.js"
if [ $2 ]; then
	scriptfile=$2
fi

js_output_file="../../resources/js/$scriptfile"

# js compiler (currently closeure)
compiler=`pwd`/compiler.jar

#search for resources/js/src/(\w\d-/.).js
pattern="resources\/js\/src\/\(\w\|\d\|-\|/\|\.\)*.js"

#search in index.php for script src includes that match pattern
#use matches to build command
for file in `grep -o $pattern $index_file` ; do
	scripts="$scripts --js=../../$file"
done

#build java command to compile scripts using closure compiler
cmd="java -jar $compiler $scripts --js_output_file=$js_output_file"
#for debugging
#echo $cmd

#run command
$cmd

#output success
echo "$js_output_file build complete"
